In [16]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv("HCICollatedData.csv")

In [18]:
num_participants = 20
num_columns = 7 

participants = ['P' + str(i) for i in range(1, 11)] + ['S' + str(i) for i in range(1, 11)]

data = []
for participant in participants:
    for i in range(num_columns):
        row = [0] * num_columns
        row[i] = 1
        row[0] = participant
        data.append(row)

column_names = ['Participant'] + ['tab_nopic_clicks', 'list_nopic_clicks',
                                  'paragraph_nopic_clicks', 'tab_pic_clicks',
                                  'list_pic_clicks', 'paragraph_pic_clicks']

result_df = pd.DataFrame(data, columns=column_names)

result_df = result_df[(result_df.iloc[:, 1:] != 0).any(axis=1)]

In [19]:
result_df

,Participant,tab_nopic_clicks,list_nopic_clicks,paragraph_nopic_clicks,tab_pic_clicks,list_pic_clicks,paragraph_pic_clicks
1,P1,1,0,0,0,0,0
2,P1,0,1,0,0,0,0
3,P1,0,0,1,0,0,0
4,P1,0,0,0,1,0,0
5,P1,0,0,0,0,1,0
...,...,...,...,...,...,...,...
135,S10,0,1,0,0,0,0
136,S10,0,0,1,0,0,0
137,S10,0,0,0,1,0,0
138,S10,0,0,0,0,1,0
139,S10,0,0,0,0,0,1

In [20]:
merged = pd.merge(df, result_df, on='Participant', how='outer')
merged

,Participant,tab-noPic-first-clicks,tab-pic-first-clicks,list-noPic-first-clicks,list-pic-first-clicks,paragraph-noPic-first-clicks,paragraph-pic-first-clicks,tab-noPic-second-clicks,tab-pic-second-clicks,list-noPic-second-clicks,...,list-noPic-second-time,list-pic-second-time,paragraph-noPic-second-time,paragraph-pic-second-time,tab_nopic_clicks,list_nopic_clicks,paragraph_nopic_clicks,tab_pic_clicks,list_pic_clicks,paragraph_pic_clicks
0,P1,4,4,0,0,1,1,4,4,0,...,X,X,2068.40,3855.70,1,0,0,0,0,0
1,P1,4,4,0,0,1,1,4,4,0,...,X,X,2068.40,3855.70,0,1,0,0,0,0
2,P1,4,4,0,0,1,1,4,4,0,...,X,X,2068.40,3855.70,0,0,1,0,0,0
3,P1,4,4,0,0,1,1,4,4,0,...,X,X,2068.40,3855.70,0,0,0,1,0,0
4,P1,4,4,0,0,1,1,4,4,0,...,X,X,2068.40,3855.70,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,S9,0,0,5,5,0,0,0,0,5,...,1077.42,1023.14,X,X,0,1,0,0,0,0
116,S9,0,0,5,5,0,0,0,0,5,...,1077.42,1023.14,X,X,0,0,1,0,0,0
117,S9,0,0,5,5,0,0,0,0,5,...,1077.42,1023.14,X,X,0,0,0,1,0,0
118,S9,0,0,5,5,0,0,0,0,5,...,1077.42,1023.14,X,X,0,0,0,0,1,0
119,S9,0,0,5,5,0,0,0,0,5,...,1077.42,1023.14,X,X,0,0,0,0,0,1

In [21]:
columns_to_convert = merged.columns.difference(['Participant'])
merged[columns_to_convert] = merged[columns_to_convert].apply(pd.to_numeric, errors='coerce')
merged

,Participant,tab-noPic-first-clicks,tab-pic-first-clicks,list-noPic-first-clicks,list-pic-first-clicks,paragraph-noPic-first-clicks,paragraph-pic-first-clicks,tab-noPic-second-clicks,tab-pic-second-clicks,list-noPic-second-clicks,...,list-noPic-second-time,list-pic-second-time,paragraph-noPic-second-time,paragraph-pic-second-time,tab_nopic_clicks,list_nopic_clicks,paragraph_nopic_clicks,tab_pic_clicks,list_pic_clicks,paragraph_pic_clicks
0,P1,4,4,0,0,1,1,4,4,0,...,NaN,NaN,2068.4,3855.7,1,0,0,0,0,0
1,P1,4,4,0,0,1,1,4,4,0,...,NaN,NaN,2068.4,3855.7,0,1,0,0,0,0
2,P1,4,4,0,0,1,1,4,4,0,...,NaN,NaN,2068.4,3855.7,0,0,1,0,0,0
3,P1,4,4,0,0,1,1,4,4,0,...,NaN,NaN,2068.4,3855.7,0,0,0,1,0,0
4,P1,4,4,0,0,1,1,4,4,0,...,NaN,NaN,2068.4,3855.7,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,S9,0,0,5,5,0,0,0,0,5,...,1077.42,1023.14,NaN,NaN,0,1,0,0,0,0
116,S9,0,0,5,5,0,0,0,0,5,...,1077.42,1023.14,NaN,NaN,0,0,1,0,0,0
117,S9,0,0,5,5,0,0,0,0,5,...,1077.42,1023.14,NaN,NaN,0,0,0,1,0,0
118,S9,0,0,5,5,0,0,0,0,5,...,1077.42,1023.14,NaN,NaN,0,0,0,0,1,0
119,S9,0,0,5,5,0,0,0,0,5,...,1077.42,1023.14,NaN,NaN,0,0,0,0,0,1

In [22]:
mask = merged['tab_nopic_clicks'] == 1
merged.loc[mask, 'sumClicks'] = merged.loc[mask, 'tab-noPic-first-clicks'] + merged.loc[mask, 'tab-noPic-second-clicks']
merged.loc[mask, 'avgTime'] = (merged.loc[mask, 'tab-noPic-first-time'] + merged.loc[mask, 'tab-noPic-second-time'])/2
merged.loc[mask, 'clicks1'] = merged.loc[mask, 'tab-noPic-first-clicks']
merged.loc[mask, 'clicks2'] = merged.loc[mask, 'tab-noPic-second-clicks']
merged.loc[mask, 'time1'] = merged.loc[mask, 'tab-noPic-first-time']
merged.loc[mask, 'time2'] = merged.loc[mask, 'tab-noPic-second-time']

In [23]:
mask = merged['list_nopic_clicks'] == 1
merged.loc[mask, 'sumClicks'] = merged.loc[mask, 'list-noPic-first-clicks'] + merged.loc[mask, 'list-noPic-second-clicks']
merged.loc[mask, 'avgTime'] = (merged.loc[mask, 'list-noPic-first-time'] + merged.loc[mask, 'list-noPic-second-time'])/2
merged.loc[mask, 'clicks1'] = merged.loc[mask, 'list-noPic-first-clicks']
merged.loc[mask, 'clicks2'] = merged.loc[mask, 'list-noPic-second-clicks']
merged.loc[mask, 'time1'] = merged.loc[mask, 'list-noPic-first-time']
merged.loc[mask, 'time2'] = merged.loc[mask, 'list-noPic-second-time']

In [24]:
mask = merged['paragraph_nopic_clicks'] == 1
merged.loc[mask, 'sumClicks'] = merged.loc[mask, 'paragraph-noPic-first-clicks'] + merged.loc[mask, 'paragraph-noPic-second-clicks']
merged.loc[mask, 'avgTime'] = (merged.loc[mask, 'paragraph-noPic-first-time'] + merged.loc[mask, 'paragraph-noPic-second-time'])/2
merged.loc[mask, 'clicks1'] = merged.loc[mask, 'paragraph-noPic-first-clicks']
merged.loc[mask, 'clicks2'] = merged.loc[mask, 'paragraph-noPic-second-clicks']
merged.loc[mask, 'time1'] = merged.loc[mask, 'paragraph-noPic-first-time']
merged.loc[mask, 'time2'] = merged.loc[mask, 'paragraph-noPic-second-time']

In [25]:
mask = merged['tab_pic_clicks'] == 1
merged.loc[mask, 'sumClicks'] = merged.loc[mask, 'tab-pic-first-clicks'] + merged.loc[mask, 'tab-pic-second-clicks']
merged.loc[mask, 'avgTime'] = (merged.loc[mask, 'tab-pic-first-time'] + merged.loc[mask, 'tab-pic-second-time'])/2
merged.loc[mask, 'clicks1'] = merged.loc[mask, 'tab-noPic-first-clicks']
merged.loc[mask, 'clicks2'] = merged.loc[mask, 'tab-noPic-second-clicks']
merged.loc[mask, 'time1'] = merged.loc[mask, 'tab-noPic-first-time']
merged.loc[mask, 'time2'] = merged.loc[mask, 'tab-noPic-second-time']

In [26]:
mask = merged['paragraph_pic_clicks'] == 1
merged.loc[mask, 'sumClicks'] = merged.loc[mask, 'paragraph-pic-first-clicks'] + merged.loc[mask, 'paragraph-pic-second-clicks']
merged.loc[mask, 'avgTime'] = (merged.loc[mask, 'paragraph-pic-first-time'] + merged.loc[mask, 'paragraph-pic-second-time'])/2
merged.loc[mask, 'clicks1'] = merged.loc[mask, 'paragraph-noPic-first-clicks']
merged.loc[mask, 'clicks2'] = merged.loc[mask, 'paragraph-noPic-second-clicks']
merged.loc[mask, 'time1'] = merged.loc[mask, 'paragraph-noPic-first-time']
merged.loc[mask, 'time2'] = merged.loc[mask, 'paragraph-noPic-second-time']

In [27]:
mask = merged['list_pic_clicks'] == 1
merged.loc[mask, 'sumClicks'] = merged.loc[mask, 'list-pic-first-clicks'] + merged.loc[mask, 'list-pic-second-clicks']
merged.loc[mask, 'avgTime'] = (merged.loc[mask, 'list-pic-first-time'] + merged.loc[mask, 'list-pic-second-time'])/2
merged.loc[mask, 'clicks1'] = merged.loc[mask, 'list-noPic-first-clicks']
merged.loc[mask, 'clicks2'] = merged.loc[mask, 'list-noPic-second-clicks']
merged.loc[mask, 'time1'] = merged.loc[mask, 'list-noPic-first-time']
merged.loc[mask, 'time2'] = merged.loc[mask, 'list-noPic-second-time']

In [31]:
columns_to_replace = ['sumClicks','avgTime','clicks1','clicks2','time1','time2']

merged[columns_to_replace] = merged[columns_to_replace].replace(0, np.nan)

In [32]:
merged

,Participant,tab-noPic-first-clicks,tab-pic-first-clicks,list-noPic-first-clicks,list-pic-first-clicks,paragraph-noPic-first-clicks,paragraph-pic-first-clicks,tab-noPic-second-clicks,tab-pic-second-clicks,list-noPic-second-clicks,...,paragraph_nopic_clicks,tab_pic_clicks,list_pic_clicks,paragraph_pic_clicks,sumClicks,avgTime,clicks1,clicks2,time1,time2
0,P1,4,4,0,0,1,1,4,4,0,...,0,0,0,0,8.0,8286.555,4.0,4.0,12284.78,4288.33
1,P1,4,4,0,0,1,1,4,4,0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,P1,4,4,0,0,1,1,4,4,0,...,1,0,0,0,2.0,2593.900,1.0,1.0,3119.40,2068.40
3,P1,4,4,0,0,1,1,4,4,0,...,0,1,0,0,8.0,3336.365,4.0,4.0,12284.78,4288.33
4,P1,4,4,0,0,1,1,4,4,0,...,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,S9,0,0,5,5,0,0,0,0,5,...,0,0,0,0,10.0,1359.760,5.0,5.0,1642.10,1077.42
116,S9,0,0,5,5,0,0,0,0,5,...,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
117,S9,0,0,5,5,0,0,0,0,5,...,0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN
118,S9,0,0,5,5,0,0,0,0,5,...,0,0,1,0,10.0,962.610,5.0,5.0,1642.10,1077.42
119,S9,0,0,5,5,0,0,0,0,5,...,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
data_ver2 = merged[['Participant', 'tab_nopic_clicks', 'list_nopic_clicks','paragraph_nopic_clicks','tab_pic_clicks',
                    'list_pic_clicks', 'paragraph_pic_clicks','sumClicks', 'avgTime', 'clicks1','clicks2', 'time1','time2']]
data_ver2 = data_ver2.sort_values(by='Participant')
data_ver2

,Participant,tab_nopic_clicks,list_nopic_clicks,paragraph_nopic_clicks,tab_pic_clicks,list_pic_clicks,paragraph_pic_clicks,sumClicks,avgTime,clicks1,clicks2,time1,time2
0,P1,1,0,0,0,0,0,8.0,8286.555,4.0,4.0,12284.78,4288.33
1,P1,0,1,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,P1,0,0,1,0,0,0,2.0,2593.900,1.0,1.0,3119.40,2068.40
3,P1,0,0,0,1,0,0,8.0,3336.365,4.0,4.0,12284.78,4288.33
4,P1,0,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,S9,1,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
115,S9,0,1,0,0,0,0,10.0,1359.760,5.0,5.0,1642.10,1077.42
116,S9,0,0,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
117,S9,0,0,0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN
119,S9,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
file_path = "Data_ver2.csv"

data_ver2.to_csv(file_path, index=False)